### ISSUE TITLE
tx_log.csv being created in wrong directory?

### ISSUE THREAD

**Issue by apkil** [IBM/AMLSim#47]
Playing with AMLSim for the first time for a dissertation project. Getting an error on this step - python3 scripts/convert_logs.py conf.json

Simulation name: sample
Load alert groups: alert_members.csv
Convert transaction list from tmp/sample/tx_log.csv to transactions.csv, cash_tx.csv and alert_transactions.csv
Traceback (most recent call last):
  File "scripts/convert_logs.py", line 912, in <module>
    converter.convert_acct_tx()
  File "scripts/convert_logs.py", line 632, in convert_acct_tx
    in_tx_f = open(self.log_file, "r")  # Transaction log file from the Java simulator
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/sample/tx_log.csv'

**Comment by nelsonjd** [comment]
@apkil I have a pr for this currently open.  You can apply the one-line fix in your local until I get it merged.
