### ISSUE TITLE
java.lang.NoSuchMethodError when running the simulator

### ISSUE THREAD

**Issue by anand-chandrashekar** [IBM/AMLSim#60]
I am trying to run the simulator on a macos:
`sh scripts/run_AMLSim.sh conf.json`

The error log is as below.
`Dec 01, 2021 11:34:48 AM amlsim.AMLSim loadAccountFile
INFO: Account CSV header: ACCOUNT_ID,CUSTOMER_ID,INIT_BALANCE,START_DATE,END_DATE,COUNTRY,ACCOUNT_TYPE,IS_SAR,TX_BEHAVIOR_ID,BANK_ID
Dec 01, 2021 11:34:48 AM amlsim.AMLSim loadAccountFile
INFO: Account CSV header: ACCOUNT_ID,CUSTOMER_ID,INIT_BALANCE,START_DATE,END_DATE,COUNTRY,ACCOUNT_TYPE,IS_SAR,TX_BEHAVIOR_ID,BANK_ID
Exception in thread "main" java.lang.NoSuchMethodError: sim.engine.Schedule.scheduleRepeating(Lsim/engine/Steppable;)Lsim/engine/IterativeRepeat;
	at amlsim.AMLSim.loadAccountFile(AMLSim.java:269)
	at amlsim.AMLSim.initSimulation(AMLSim.java:135)
	at paysim.PaySim.start(PaySim.java:115)
	at amlsim.AMLSim.executeSimulation(AMLSim.java:433)
	at amlsim.AMLSim.runSimulation(AMLSim.java:108)
	at amlsim.AMLSim.main(AMLSim.java:550)
(base) anand@my AMLSim % javac -version
javac 1.8.0_292

**Comment by anand-chandrashekar** [comment]
Here are the contents of my jars folder.
```
(base) anand@my AMLSim % ls jars
JSAP-2.1.jar					fastutil-8.2.3.jar				paysim.jar
README.md					json-20180813.jar				slf4j-api-1.7.9.jar
byte-buddy-1.11.19.jar				junit-platform-console-standalone-1.8.1.jar	slf4j-simple-1.7.25.jar
byte-buddy-agent-1.11.19.jar			mason.18.jar					sux4j-4.2.0.jar
commons-math3-3.6.1.jar				mysql-connector-java-8.0.27.jar			webgraph-3.6.1.jar
dsiutils-2.5.4.jar				objenesis-3.2.jar
```

**Comment by nelsonjd** [comment]
@anand-chandrashekar 
In the error message I noticed `sim.engine.Schedule.scheduleRepeating(Lsim/engine/Steppable;)Lsim/engine/IterativeRepeat;`
I don't know where `Lsim` is coming from but it should be `sim/engine/Steppable`
